name: Build and Deploy to Azure Web App for Containers via ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image to ACR
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-suitability-app:latest .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-suitability-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY_LOGIN_SERVER }}/cloud-suitability-app:latest